
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’9.0’

target 'HLTools' do
use_frameworks!

pod 'JTAppleCalendar', '~> 7.0’

#pod 'WMPlayer', '~> 3.0.6'

#pod 'SnapKit', '~> 4.0.0'

end